import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml
// and ../apis/openapi-reports.yaml.
// Regenerate with: npm run gen-api-docs:all
import apiSidebar from './docs/api-reference/rest/sidebar';
import apiReportsSidebar from './docs/api-reference/rest-reports/sidebar';

/**
 * Top-level categories mirror the shape shared across warehouse-systems
 * documentation sites: Overview, Operations, Development, Business
 * Context, Domain-Driven Design (plus the ddd-crew artifact pack), API
 * Reference, API Reference (Reports), Ecosystem, MCP, Architecture
 * Decision Records.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      link: {type: 'doc', id: 'overview/introduction'},
      items: ['overview/introduction', 'overview/architecture', 'overview/quickstart'],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/configuration',
        'operations/runbook',
        'operations/observability',
        'operations/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: ['development/testing'],
    },
    'business-context/domain-vision',
    'ddd/subdomain-classification',
    'ddd/use-cases',
    {
      type: 'category',
      label: 'DDD artifacts (ddd-crew)',
      link: {type: 'doc', id: 'ddd/ddd-artifacts'},
      items: [
        'ddd/core-domain-chart',
        'ddd/bounded-context-canvas',
        'ddd/aggregate-design-canvas',
        'ddd/domain-message-flow',
        'ddd/eventstorming',
        'ddd/ubiquitous-language',
        'ddd/class-diagram',
        'ddd/entity-relationship',
        'ddd/sequence-diagrams',
        'ddd/domain-events',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/rest/labor-performance-api'},
      items: [...apiSidebar],
    },
    {
      type: 'category',
      label: 'Reports API Reference',
      link: {type: 'doc', id: 'api-reference/rest-reports/labor-performance-reports-api'},
      items: [...apiReportsSidebar],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      items: ['ecosystem/context-map', 'ecosystem/integration'],
    },
    {
      type: 'category',
      label: 'MCP',
      items: ['mcp/tools', 'mcp/governance-charter'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/about'},
      items: [
        'adr/0001-hexagonal-ports-and-adapters',
        'adr/0002-new-bounded-context-not-extension-of-workforce-or-fulfillment',
        'adr/0003-kafka-choreography-consumer-of-fulfillment-execution',
        'adr/0004-standard-frozen-at-completion-time-not-recomputed',
        'adr/0005-associate-trend-and-coaching-flag',
        'adr/0006-mean-actual-seconds-independent-of-standard',
        'adr/0007-analytical-data-product',
        'adr/0008-standard-metrics-convention',
        'adr/0009-mcp-inbound-adapter',
        'adr/0010-transactional-outbox',
        'adr/0011-rest-auth-static-bearer-scopes',
        'adr/0012-remove-rest-auth-layer',
        'adr/0013-labor-performance-integration-events',
        'adr/0014-labor-utilization-idleness',
        'adr/0015-optional-travel-component-on-labor-standard',
        'adr/0016-idempotency-key-middleware',
        'adr/0017-kafka-dlq-and-graceful-shutdown',
        'adr/0018-kafka-writer-hash-balancer',
        'adr/0019-horizontal-autoscaling-and-pgxpool-tuning',
        'adr/0020-migrations-direct-postgres-connection',
        'adr/0021-cloudevents-mandatory-event-envelope',
        'adr/0022-optimistic-concurrency-one-open-standard',
        'adr/0023-housekeeping-sweeper',
        'adr/0024-labor-mfe-frontend-remote',
        'adr/0025-rfc7807-problem-details',
        'adr/0026-arch-go-fitness-suite',
        'adr/0027-bootretry-and-startup-probe',
        'adr/0028-gateway-api-httproute',
        'adr/0029-kafka-writer-durability',
        'adr/0030-mcp-eval-and-governance-gates',
        'adr/0031-analytics-consumer-atomic-claim-and-retry',
      ],
    },
  ],
};

export default sidebars;
